config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show', as: 'root'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  get '/password/edit', to: "passwords#edit", as: :edit_password
  post '/password/edit', to: "passwords#update"

  resources :questions do
    resources :best_answers, only: [:create]
  end

  resources :upvotes, only: [:create, :destroy]
  resources :downvotes, only: [:create, :destroy]

  resources :users
  resources :answers, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :user_permissions, only: [:update]

  get 'authenticate_user', to: 'authentication#update'
  namespace :api do
    namespace :v1 do
      namespace :users do
        get "/by_reputation", to: "users_by_reputation#index"
        get "/banned", to: "users_banned#index"
      end
      get :token, controller: 'base'

      resources :questions, only:[:create]

      namespace :questions do
        get '/recent_questions', to: 'questions_recent#index'
      end

      resources :users, only: [:show, :index] do
      end

    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :best_answer, class_name: 'Answer', required: false
  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  validates :title, :body, presence: true
  has_many :upvotes, as: :upvoted, dependent: :destroy
  has_many :downvotes, as: :downvoted, dependent: :destroy

  def self.order_by_update
    order(:updated_at).reverse_order
  end

  def find_user_object
    user
  end

  def find_category
    category.name
  end

  def answer_count
    answers.count
  end

  def current_user_upvote_correction(creator_id)
    if upvotes.where(creator: creator_id).exists?
      upvotes.where(creator:creator_id).destroy_all
    end
  end

  def current_user_downvote_correction(creator_id)
    if downvotes.where(creator: creator_id).exists?
      downvotes.where(creator:creator_id).destroy_all
    end
  end

  def self.show_all_questions(category)
    if category
      where(category: Category.find(category))
    else
      order_by_update
    end
  end

  def question_upvotes
    upvotes.count
  end

  def question_downvotes
    downvotes.count
  end

  def net_votes
    question_upvotes - question_downvotes
  end

  def sort_by_best_answer
    if best_answer
      [best_answer] + answers.where.not(id: best_answer.id).to_a
    else
      answers
    end
  end

  def question_reputation
    upvotes.count - downvotes.count
  end

  def find_user_id
    user.id
  end

  def self.recent_questions
    find_by_sql([
      "select q.id, q.title, q.body, q.created_at, q.category_id, c.name as category_name
      from questions q
      inner join categories c on q.category_id = c.id
      order by q.created_at DESC
      limit 5;"])
  end
end

app/controllers/api/v1/questions/questions_recent_controller.rb
class Api::V1::Questions::QuestionsRecentController < ApplicationController
  def index
    render json: Question.recent_questions, each_serializer: QuestionRecentSerializer
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  def create
    Question.create(question_params)
  end

private

  def question_params
    params.permit(:title, :body, :category_id, :user_id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.order_by_update.page(params[:page]).per(25)
    @presenter = Presenter.new
  end

  def new
    if current_user
      @question = current_user.questions.new
      @categories = Category.all
    else
      redirect_to login_path
    end
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      flash[:success] = "Question successfully created!"
      redirect_to question_path(@question)
    else
      @categories = Category.all
      flash.now[:danger] = "Failed to create question"
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answers.new
    @comment = @question.comments.new
    @upvote = Upvote.new
    @downvote = Downvote.new
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      flash[:success] = "Your question was deleted successfully!"
      redirect_to root_path
    else
      flash[:danger] = "Failed to delete the question"
      redirect_to question_path(@question)
    end
  end

  def edit
    @question = Question.find(params[:id])
    @categories = Category.all
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:success] = "Your question was edited successfully!"
      redirect_to question_path(@question)
    else
      flash.now[:danger] = "Failed to edit question. Please try again."
      redirect_to edit_question_path(@question)
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :category_id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def best_answer?(question, answer)
    question.best_answer_id == answer.id
  end
end

app/views/questions/edit.html.erb
<h2>Question</h2>

<div class="row">
  <div class="col s12 m12">
    <div class="card-panel white">
      <span class="black-text">
          <%= form_for @question do |f| %>
        <div id="question-title" >
          <div class="divider"></div>
          <h5><%= f.text_field :title, placeholder: "Title" %><br></h5>
          <div class="divider"></div>
        </div>
        <br>
        <div id="question-body" >
          <%= f.text_area :body, placeholder: "Body" %><br>
          <%= f.collection_select(:category_id, @categories, :id, :name, prompt: "Choose a Category", class: "browser-default") %>
          <%= f.submit "Submit" %>
        </div>
        <% end %>
      </span>
      <br>
      <div class="card-action">
        <%= @question.updated_at.strftime("%D at %r") %><br>
        <%= @question.find_user %><br>
      </div>
        <% if !@question.comments.empty? %>
          <%= render 'comments/questioncomments' %>
        <% end %>
    </div>
  </div>
</div>

<h4><%= @question.answer_count %> Answers</h4>
<div class="row">
  <div class="question-answers">
    <% @question.answers.each do |answer| %>
      <div class="question-answer">
        <div class="col s12 m12">
          <div class="card-panel white">
            <span class="black-text">
              <%= answer.body %><br>
            </span>
            <% if !answer.comments.empty? %>
              <%= render partial: "comments/answercomments", locals: { answer: answer } %>            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<h1 class="questions_header">All Questions</h1>

<div class="row">
  <div class="col s12 m4 l3">
    <div class="row">
      <div class="col s12 m12">
        <div class="card white">
          <div class="card-content black-text">
            <div class="categories">
              <span class="card-title">Categories</span>
              <% @presenter.all_categories.each do |category| %>
              <%= link_to "#{category.name}", questions_path(:category => category.id)%>
              <br>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col s12 m8 l9">
    <div class="row">
      <div class="col s12 m12">
        <div class="card white">
          <div class="card-content black-text">
            <div class="questions-by-category">
              <% if params[:category].nil? %>
              <% else %>
                <span class="card-title">Questions by Category: <%=@presenter.category_name(params[:category]) %> </span>
              <% end %>
              <table class="striped">
                <thead>
                  <tr>
                    <th>Votes</th>
                    <th>Answers</th>
                    <th>Title</th>
                    <th>Creator</th>
                    <th>Category</th>
                    <th>Updated_at</th>
                  </tr>
                 </thead>

                 <tbody>
                   <% @questions.show_all_questions(params[:category]).each do |question| %>
                   <tr>
                     <td><p class="center"><%= question.net_votes %></p></td>
                     <td><p class="center"><%= question.answers.count %></p></td>
                     <td><a href=<%= question_path(question.id) %>><%=question.title%></a></td>
                     <td><%= link_to question.find_user, user_path(question.find_user_object)%></td>
                     <td><%= question.find_category %></td>
                     <td><%=question.updated_at.strftime("%D at %r")%></td>
                   </tr>
                   <% end %>
                 </tbody>
               </table>
             </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="center"><%= paginate @questions.show_all_questions(params[:category]) %></div>

app/views/questions/new.html.erb
<div id="new-question-form">
<%= form_for @question do |f| %>
  <span>
    <%= f.text_field :title, placeholder: "Title" %>
    <%= show_errors(@question, :title) %>
  </span>
  <span>
  <%= f.text_area :body, placeholder: "Body" %>
  <%= show_errors(@question, :body) %>
  </span>
  <span>
  <%= f.collection_select(:category_id, @categories, :id, :name, prompt: "Choose a Category", class: "browser-default", :selected => params[:category]) %>
  <%= show_errors(@question, :category) %>
  </span>
  <%= f.submit "Submit", class: "white-text waves-effect blue btn-large" %>
<% end %>
</div>

app/views/questions/show.html.erb
<h2>Question</h2>
<% if display_block_button?(@question) %>
  <div id='deactivate-user-button' class='right card-action'>
    <%= button_to "Deactivate User", user_permission_path(@question.user), method: :put, class: "waves-effect red darken-1 waves-light btn right" %>
  </div>
<% elsif display_unblock_button?(@question) %>
  <div id='reactivate-user-button' class='right card-action'>
    <%= button_to "Reactivate User", user_permission_path(@question.user), method: :put, class: "waves-effect red darken-1 waves-light btn right" %>
  </div>
<% end %>
<div class="row">
  <div class="col s12 m11 right">
    <div class="card white question">
      <div class="card-content black-text">
        <div class="card-title" id="question-title">
          <div class="divider"></div>
          <h3><%= @question.title %><br></h3>
          <div class="divider"></div>
        </div>
        <div id="question-body" >
          <%= @question.body %>
          <br><br>
          <div id="question-details" class="right card-action">
            <p>Author: <%= link_to @question.find_user, user_path("#{@question.find_user_id}")%> Updated: <%= @question.updated_at.strftime("%D at %r") %></p><br>
          </div>
          <br><br>
        </div>
      </div>
      <div class="card-action">
        <div style="display:inline-block; vertical-align: middle;">
          <div class="category-badge">
            <button class="btn grey disabled center" ><%= @question.find_category %></button>
          </div>
          <div class="left" id="edit-question">
            <% if current_users_question?(@question) %>
                <%= button_to "Edit Question", edit_question_path(@question), method: :get, class: "white-text waves-effect blue btn-small" %>
            <% end %>
          </div>
          <div class="right" id="delete-question">
              <% if current_users_question?(@question)%>
                <%= button_to "Delete Question", question_path(@question), method: :delete, class: "white-text waves-effect red darken-4 btn-small" %>
              <% elsif current_admin? %>
                <%= button_to "Delete Question", question_path(@question), method: :delete, class: "right red darken-4 btn-small" %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col s12 m1 left">
    <%= render 'votes/question_vote_buttons' %>
  </div>
</div>

<div class="row">
  <div id="question-comments">
    <% if @question.comments.check_comments %>
        <% @question.comments.each do |comment| %>
          <% unless comment.body.nil? || !comment.persisted? %>
            <div class="col s12 m10 right">
              <%= render 'comments/questioncomments', comment: comment %>
            </div>
            <div class="col s12 m1 right">
              <%= render 'votes/question_comment_vote_buttons', comment: comment %>
            </div>
          <% end %>
        <% end %>
    <% end %>
  </div>
</div>

<div class="row comment-on-question">
  <%= render 'comments/comment_on_question' %>
</div>

<br><br>

<h4><%= @question.answer_count %> Answers</h4>

<div class="row">
  <div class="question-answers">
    <% @question.sort_by_best_answer.each do |answer| %>
      <% unless answer.body.nil? || !answer.persisted? %>

        <div class="col s12 m11 right">
          <%= render 'answers/question_answers', answer: answer %>
        </div>

        <div class="col s12 m1 left">
          <%= render 'votes/answer_vote_buttons', answer: answer %>
        </div>

        <div class="col s12 m1 best-answer-badge">
          <% if best_answer?(@question, answer) %>
            <div id="best-answer">
              <i class="material-icons icon-green right">check</i>
            </div>
          <% end %>
        </div>

        <div class="row comment-on-answer col s12 m10 right">
          <%= render 'comments/comment_on_answer', answer: answer %>
        </div>

        <div class="row">
          <div id="answer-comments" class="blue-text">
            <% answer.comments.each do |comment| %>
              <% unless comment.body.nil? || !comment.persisted? %>
                  <div class="col s12 m10 right">
                    <%= render 'comments/answercomments', comment: comment %>
                  </div>
                  <div class="col s12 m1 right">
                    <%= render 'votes/answer_comments_vote_buttons', comment: comment %>
                  </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div id="answer-question" class="row">
  <h5>Answer this question</h5>
  <%= form_for [@question, @answer], url: { controller: "answers", action: "create" } do |f| %>
  <%= f.hidden_field :question, :value => @question.id %>
  <%= f.text_area :body, placeholder: "Enter text" %>
  <%= show_errors(@answer, :body) %>
  <%= f.submit "Submit", class: "white-text waves-effect blue btn-small" %>
  <% end %>
</div>