config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show', as: 'root'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  get '/password/edit', to: "passwords#edit", as: :edit_password
  post '/password/edit', to: "passwords#update"

  resources :questions do
    resources :best_answers, only: [:create]
  end

  resources :upvotes, only: [:create, :destroy]
  resources :downvotes, only: [:create, :destroy]

  resources :users
  resources :answers, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :user_permissions, only: [:update]

  get 'authenticate_user', to: 'authentication#update'
  namespace :api do
    namespace :v1 do
      namespace :users do
        get "/by_reputation", to: "users_by_reputation#index"
        get "/banned", to: "users_banned#index"
      end
      get :token, controller: 'base'

      resources :questions, only:[:create]

      namespace :questions do
        get '/recent_questions', to: 'questions_recent#index'
      end

      resources :users, only: [:show, :index] do
      end

    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :answers
  has_many :comments
  has_many :password_tokens
  has_many :questions
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :upvotes, dependent: :destroy
  has_many :downvotes, dependent: :destroy

  validates :name, :email, :phone, :reputation, presence: true

  before_create -> { self.auth_token = SecureRandom.hex }

  def comments_to_recent_activity
    Comment.comments_to_user_activity(self.id)[0..4]
  end

  def recent_questions
    questions.last(5).reverse!
  end

  def recent_answers
    answers.last(5).reverse!
  end

  def admin?
    roles.exists?(name: "admin")
  end

  def registered_user?
    roles.exists?(name: "registered_user")
  end

  def blocked_user?
    roles.exists?(name: "blocked_user")
  end

  def deactivate
    user_roles.destroy_all
    user_roles.create(role: Role.find_by(name: "blocked_user"))
  end

  def reactivate
    user_roles.destroy_all
    user_roles.create(role: Role.find_by(name: "registered_user"))
  end

  def upvote_count
    upvotes.count
  end

  def downvote_count
    downvotes.count
  end

  def reputation_count
    upvote_count - downvote_count + best_answer_count
  end

  def best_answer_count
    answers.joins(:best_question).count
  end

  def self.by_reputation
    order(:reputation).reverse_order[0..9]
  end

  def self.need_to_block
    joins(:roles).where("roles.name != 'blocked_user'")
    .where("users.reputation <= -10")
  end

  def self.banned
    find_by_sql([
      "select u.id, u.name, u.email, u.reputation, r.name AS status
      from users u
      inner join user_roles ur on u.id = ur.user_id
      inner join roles r on ur.role_id = r.id
      where r.name = 'blocked_user';"
      ])
  end
end

app/controllers/api/v1/users/users_banned_controller.rb
class Api::V1::Users::UsersBannedController < ApplicationController

  def index
    render json: User.banned, each_serializer: UserBannedSerializer
  end
end

app/controllers/api/v1/users/users_by_reputation_controller.rb
class Api::V1::Users::UsersByReputationController < ApplicationController
  def index
    render json: User.by_reputation
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def show
    render json: User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      session[:user_id] = @user.id
      flash[:success] = "For full user privileges, check your e-mail and validate your account."
      redirect_to user_path(@user)
    else
      flash.now[:danger] = "Account creation unsuccessful"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit

  end

  def update
    if current_user.update_attributes(user_update_params)
      redirect_to user_path(current_user)
    else
      flash.now[:danger] = "Account update unsuccessful"
      render :edit
    end
  end

  private

  def user_update_params
    params.require(:user).permit(:email, :image, :phone)
  end

  def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :image,
                                 :password,
                                 :password_confirmation,
                                 :phone)
  end
end

app/views/users/_user-show-answers.html.erb
  <div class="col s12 m6">
    <div class="card-small blue lighten-3">
      <table class='centered' id='user-show-answers'>
        <thead>
          <tr>
              <th>Your Most Recent Answers</th>
          </tr>
        </thead>
        <tbody>
          <% @user.recent_answers.each do |answer|%>
            <tr>
              <td>
                <%= link_to answer.question.title, question_path(answer.question) %></br>
                Updated at: <%= answer.updated_date_and_time %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/_user-show-comments.html.erb
<div class="row">
  <div class="col s12 m6">
    <div class="card-large blue lighten-3">
      <table class='centered' id='user-show-comments'>
        <thead>
          <tr>
              <th>Recent Comments to Your Activity</th>
          </tr>
        </thead>
        <tbody>
          <% @user.comments_to_recent_activity.each do |comment|%>
            <tr>
              <td>
                <%= link_to comment.source_question.title, question_path(comment.source_question) %></br>
                  Updated at: <%= comment.updated_date_and_time %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>

app/views/users/_user-show-questions.html.erb
<div class="row">
  <div class="col s12 m6">
    <div class="card-large blue lighten-3">
      <table class='centered' id='user-show-questions'>
        <thead>
          <tr>
              <th>Your Most Recent Questions</th>
          </tr>
        </thead>
        <tbody>
          <% @user.recent_questions.each do |question|%>
            <tr>
              <td>
                <%= link_to question.title, question_path(question) %> </br>
                Updated at: <%= question.updated_date_and_time %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>

app/views/users/_user_info.html.erb
<div class="row">
  <div class="col s12 m6">
    <div class="card blue lighten-1">
      <div class="card-content black-text">
        <table class='centered' id='user-info-table'>
          <thead>
            <tr>
                <th>            </th>
                <th>            </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                E-Mail:
              </td>
              <td>
                <%= @user.email %>
              </td>
            </tr>
            <tr>
              <% if current_user == @user %>
                <td>
                  Phone:
                </td>
                <td>
                  <%= @user.phone %>
                </td>
              <% end %>
            </tr>
            <tr>
              <td>
                Reputation:
              </td>
              <td id='user-street-rep'>
                <%= @user.reputation %>
              </td>
            </tr>
            <tr>
              <% if current_user == @user %>
                <td>
                  <%= link_to "Edit User Profile", edit_user_path(current_user), style: "color: white" %>
                </td>
                <td>
                  <%= link_to "Change Password", edit_password_path, style: "color: white" %>
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
  </div>
  <div class="col s12 m6">
    <div class="card blue lighten-1" id='user-avatar'>
      <div>
      <%= gravatar_image_tag @user.email, alt: @user.name, gravatar: { size: 200, default: "http://www.ulyces.co/wp-content/plugins/tia-author-image/default_user_icon.jpg" }, class: "user-pic" %>
      <hr>
        <div class="user-name" >
          Name: <%= @user.name %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col s12 m12">
    <div class="card-panel blue lighten-5">
      <span class="center black-text">
        <h4>Update Your Account</h4><br>
        <%= form_for(current_user) do |f| %>
            <%=  f.label :email %>
            <%=  f.email_field :email %>
            <%= show_errors(current_user, :email) %>
            <%=  f.label :phone %>
            <%=  f.telephone_field :phone %>
            <%= show_errors(current_user, :phone) %>
            <%= f.submit "Save", class: "waves-effect blue darken-1 waves-light btn-large" %>
            <%= link_to "Cancel", user_path(current_user), class: "waves-effect red darken-1 waves-light btn-large" %>
        <% end %>
      </span>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col s12 m12">
    <div class="card-panel blue lighten-5">
      <span class="center black-text">
        <h4>Create Your Account</h4><br>
        <%= form_for(@user) do |f| %>
            <%=  f.label :name %>
            <%=  f.text_field :name%>
            <%=  f.label :email, "Email (will be used for Gravatar if applicable)" %>
            <%=  f.email_field :email %>
            <%=  f.label :phone %>
            <%=  f.telephone_field :phone %>
            <%=  f.label :password %>
            <%=  f.password_field :password %>
            <%=  f.label :password_confirmation %>
            <%=  f.password_field :password_confirmation %>
            <%= f.submit "Create Account", class: "waves-effect blue darken-1 waves-light btn-large" %>
        <% end %>
      </span>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col s12 m12" id='user-info'>
    <div class="card-panel blue lighten-3">
      <span class="center black-text">
        <h4>Your Account Information</h4><br>
      </span>
      <%= render 'users/user_info' %>
    </div>
  </div>
</div>
  <%= render 'users/user-show-questions' %>
  <%= render 'users/user-show-answers' %>
  <%= render 'users/user-show-comments' %>
  <% if current_admin? %>
    <%= render 'admin/users-to-deactivate' %>
  <% end %>