config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show', as: 'root'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  get '/password/edit', to: "passwords#edit", as: :edit_password
  post '/password/edit', to: "passwords#update"

  resources :questions do
    resources :best_answers, only: [:create]
  end

  resources :upvotes, only: [:create, :destroy]
  resources :downvotes, only: [:create, :destroy]

  resources :users
  resources :answers, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :user_permissions, only: [:update]

  get 'authenticate_user', to: 'authentication#update'
  namespace :api do
    namespace :v1 do
      namespace :users do
        get "/by_reputation", to: "users_by_reputation#index"
        get "/banned", to: "users_banned#index"
      end
      get :token, controller: 'base'

      resources :questions, only:[:create]

      namespace :questions do
        get '/recent_questions', to: 'questions_recent#index'
      end

      resources :users, only: [:show, :index] do
      end

    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
    @presenter = Presenter.new
  end
end

app/views/home/_welcome_jumbotron.html.erb
<div class="row">
  <div class="col s12 m12">
    <div class="card-panel blue lighten-5" id='welcome_jumbotron'>
      <span class="center black-text">
        <h4>Join the Stack Overflow Community</h4><br>
        <p>Stack Overflow is a community of 6.9 million programmers, just like you, helping each other.</p>
        <p>Join them; it only takes a minute:</p>
        <div class="center"><%= button_to "Create Account", new_user_path, method: "get", class: "waves-effect blue darken-1 waves-light btn-large" %></div>
      </span>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<% if current_user.nil? %>
  <%= render 'home/welcome_jumbotron' %>
<% end %>

<div class="row">
  <div class="col s12 m4 l3">
    <div class="row">
      <div class="col s12 m12">
        <div class="card white">
          <div class="card-content black-text">
            <div class="categories">
              <span class="card-title">Categories</span>
              <% @presenter.all_categories.each do |category| %>
              <%= link_to "#{category.name}", root_path(:category => category.id)%>
              <br>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col s12 m8 l9">
    <div class="row">
      <div class="col s12 m12">
        <div class="card white">
          <div class="card-content black-text">
            <div class="recent-activity">
              <% if params[:category].nil? %>
                <span class="card-title">Recent Activity</span>
              <% else %>
                <span class="card-title">Recent Activity: <%=@presenter.category_name(params[:category]) %> </span>
              <% end %>
              <table class="bordered">
                <thead>
                  <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>

                <tbody>
                  <div class="root-questions">
                    <% @presenter.show_questions(params[:category]).each do |question| %>
                      <tr>
                        <td>Answers: <%= question.answers.count %></td>
                        <td><a href=<%= question_path(question) %> class="collection-item"><%= question.title %></a></td>
                        <td><p>Updated: <%= question.updated_at.strftime("%D") %></p></td>
                      </tr>
                    <% end %>
                  </div>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>