config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show', as: 'root'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  get '/password/edit', to: "passwords#edit", as: :edit_password
  post '/password/edit', to: "passwords#update"

  resources :questions do
    resources :best_answers, only: [:create]
  end

  resources :upvotes, only: [:create, :destroy]
  resources :downvotes, only: [:create, :destroy]

  resources :users
  resources :answers, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :user_permissions, only: [:update]

  get 'authenticate_user', to: 'authentication#update'
  namespace :api do
    namespace :v1 do
      namespace :users do
        get "/by_reputation", to: "users_by_reputation#index"
        get "/banned", to: "users_banned#index"
      end
      get :token, controller: 'base'

      resources :questions, only:[:create]

      namespace :questions do
        get '/recent_questions', to: 'questions_recent#index'
      end

      resources :users, only: [:show, :index] do
      end

    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_one :best_question, class_name: "Question", inverse_of: :best_answer, foreign_key: :best_answer_id
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :upvotes, as: :upvoted, dependent: :destroy
  has_many :downvotes, as: :downvoted, dependent: :destroy
  validates :body, presence: true

  def self.populate_answer(comment_params)
    if comment_params[:answer]
      Answer.find(comment_params[:answer])
    else
      Answer.new(question_id: comment_params[:question])
    end
  end

  def current_user_upvote_correction(creator_id)
    if upvotes.where(creator: creator_id).exists?
      upvotes.where(creator:creator_id).destroy_all
    end
  end

  def current_user_downvote_correction(creator_id)
    if downvotes.where(creator: creator_id).exists?
      downvotes.where(creator:creator_id).destroy_all
    end
  end

  def answer_reputation
    upvotes.count - downvotes.count
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :require_user

  def create
    @question = Question.find(params[:answer][:question])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @comment = @question.comments.new
    @upvote = Upvote.new
    @downvote = Downvote.new
    if @answer.save
      flash[:success] = "You answered the question!"
      redirect_to question_path(@question)
    else
      flash.now[:danger] = "Your comment was not successful."
      render "questions/show"
    end
  end

  def destroy
    Answer.destroy(params[:id])
    redirect_to request.referrer
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def require_user
    unless current_user
      question = Question.find(params[:answer][:question])
      flash[:danger] = "You must be logged in to do that."
      redirect_to question_path(question)
    end
  end
end

app/views/answers/_question_answers.html.erb
<div class="card white black-text">
  <div class="card-content">
    <div class="answer-body">
      <h5><%= answer.body %><br></h5>
    </div>
    <br>
    <div id="answer-details" class="right card-action">
      <p>Author: <%= link_to answer.find_user, user_path("#{answer.find_user_id}") %> Updated: <%= answer.updated_at.strftime("%D at %r") unless answer.updated_at.nil? %></p><br>
    </div>
      <br><br>
  </div>
  <div class="card-action">
    <div style="display:inline-block; vertical-align: middle;">
      <div id='answer-delete-button' class="left">
        <% if current_users_answer?(answer) %>
        <%= button_to "Delete Answer","/answers/#{answer.id}", method: :delete, params: { id: answer.id}, class: "white-text waves-effect red darken-4 btn-small "%></br>
        <% elsif current_admin? %>
        <%= button_to "Delete Answer","/answers/#{answer.id}", method: :delete, params: { id: answer.id}, class: "white-text waves-effect red darken-4 btn-small "%></br>
        <% end %>
      </div>

      <% if current_users_question?(@question) && !best_answer?(@question, answer) %>
      <div class="best-answer-button right">
        <%= form_tag question_best_answers_path(@question), method: :post do %>
        <%= hidden_field_tag :best_answer_id, answer.id %>
        <%= submit_tag "Select As Best Answer", class: "white-text waves-effect green btn-small" %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>